llm:
  engine: "server"       # "phi3", "gpt", "server"

  # 서버 설정
  server:
    url: "http://localhost:8080"
    endpoint_sync: "/chat"        # sync (normal JSON response)
    endpoint_stream: "/chat_stream"  # streaming response
    timeout_sec: 300
    payload_mode: "both"   # "messages" | "prompt" | "both"
    temperature: 0.7
    top_p: 1.0

  # 스트림 설정
  chat_response_streaming:
    enabled: true
  
  classify_chat_ai: "false"
  
img_to_text:
  engine: "clip"

  option:
    image_encoder_path: "data/clip_onnx/clip_image_encoder.onnx"
    text_encoder_path: "data/clip_onnx/text_encoder.onnx"
    text_features_norm: "data/text_features_cache.npy" # should be already normalized
    text_features_labels: "data/text_features_labels.txt" # txt file

tts:
  option:
    voice_path: "data/tts_piper/en_US-bryce-medium.onnx"
